---
title: "A computational Cultural Transmission model of burial rites in Central, Northern and North-western Europe"
author: "Clemens Schmid"
output: pdf_document
---

Burial rites are often treated as an archaeological indicator of ideological affiliation and their spatial and social distribution is a vital research question in both regional and global studies. Bronze age archaeology traditionally focusses on two major dimensions to categorise burials -- although there's an immense variability of attendant phenomena within this spectrum: Flat graves versus burial mounds and cremation versus inhumation. These traits are an indispensable ingredient for common narratives of cultural interaction and shift. The latter can be explored through Cultural Evolution theory.

Cultural Evolution provides a general simulation framework to parametrize population level processes and the scale of exchange necessary to produce observed distribution patterns. From its point of view, burial rites are extraordinary traits: Following Dunnels^1^ distinction between functional and stylistic based on relevance for selection, burial rites can be handled as neutral variants. As demonstrated by Neiman^2^ drift and intergroup transmission as opposed to natural selection should therefore be the decisive processes for their expansion. On the other hand funerals touch upon personal loss and profound religious beliefs: They are not short-lived fashion and most probably well interlinked with other -- many archaeologically inaccessible -- traits.

This presentation is a longer interpretative lecture based on the master thesis I'm currently writing. To study the diffusion of burial rites, I employ the dataset RADOB-B^3^ which contains more then two thousand bronze age ^14^C dates of graves from Central, Northern and North-western Europe. Based on this data I construct regional time series that show how the behaviours mound construction, inhumation and cremation change over time. Beyond that I implement a computational model that allows to explore bronze age population parameters like the dynamic of group size development, or the degree intergroup idea transmission.

***

^1^ Dunnell, Robert C., ‘Style and Function: A Fundamental Dichotomy’, American Antiquity, 43 (1978), 192
 
^2^ Neiman, Fraser D., ‘Stylistic Variation in Evolutionary Perspective: Inferences from Decorative Diversity and Interassemblage Distance in Illinois Woodland Ceramic Assemblages’, American Antiquity, 60 (1995), 7–36 <https://doi.org/10.2307/282074>

^3^ Kneisel, Jutta, Martin Hinz, and Christoph Rinne, ‘Radon-B’, 2013 <http://radon-b.ufg.uni-kiel.de.>

***

I write my thesis at Kiel University. It is supervised by PD Dr. Oliver Nakoinz (oliver.nakoinz@ufg.uni-kiel.de) and Dr. Martin Hinz (martin.hinz@ufg.uni-kiel.de).
