---
title: "SAA"
output: pdf_document
author: Clemens Schmid
---

## A Population Graph based Style Transmission model

The now classic Neiman (1995) is a baseline for many influential applications of Cultural Transmission that explore Stylistic Variability in archaeology. It and many of its successors represent social interaction and generational development in a deliberately simplified way to facilitate the exploration of parameters and algebraic analysis. While justified, this omits both the theoretical trajectories of information transmission elaborated by Cavalli-Sforza and Feldman (1981) as well as the insights archaeologists have gained through social network analysis.

This paper explores an alternative, agent-based simulation framework that attempts to be more flexible: a diachronic population graph is established as a landscape, in which ideas as entities with individual agency seek expansion -- the meme's eye view. The social network can be constructed to represent archaeological knowledge concerning population size development, the degree of intra- and intergroup exchange or spatial or cultural patterns of interaction. Ideas may be long-term static or evolving over time, selectively neutral or functionally different, distributed randomly or according to real world examples. 

Population graph generation and idea expansion simulation are implemented in R and C++ and accessible with an R interface -- but computationally expensive. The presentation will elaborate on the concept and show an example application. 

Neiman, F. D. (1995). Stylistic Variation in Evolutionary Perspective: Inferences from Decorative Diversity and Interassemblage Distance in Illinois Woodland Ceramic Assemblages. American Antiquity, 60(1), 7–36. https://doi.org/10.2307/282074

Cavalli-Sforza, L. L., & Feldman, M. W. (1981). Cultural transmission and evolution: a quantitative approach. Princeton, N.J: Princeton University Press.

